# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturemodel',
            name='picture',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
